name: SDKman! runner

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdkversion: [8, 11, 12]
        jdkpostfix: [j9-adpt, hs-adpt]
    
    steps:
    - name: Download SDKMAN!
      run: |
        curl -sL https://get.sdkman.io | bash
        echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        jdkversion=${{ matrix.jdkversion }}
        echo jdk major version $jdkversion
        jdkpostfix=${{ matrix.jdkpostfix }}
        echo jdk postfix $jdkpostfix
        echo perl command 1 "/($jdkversion\.\d+\.\d+.\w+).*$jdkpostfix/gm && print $1"
        echo perl command 2 "/('$jdkversion'\.\d+\.\d+.\w+).*'$jdkpostfix'/gm && print $1"
        JSDK=sdk list java | perl -n -e "if /('$jdkversion'\.\d+\.\d+.\w+).*'$jdkpostfix'/ print $1"
        echo found jdk version $JSDK
        sdk install java $JSDK
        unset JAVA_HOME
        java -Xmx32m -version
        javac -J-Xmx32m -version
