name: SDKman! runner

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdkversion: [8, 11, 12]
        jdkpostfix: [j9-adpt, hs-adpt]
    
    steps:
    - name: Download SDKMAN!
      run: |
        curl -sL https://get.sdkman.io | bash
        echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        jdkversion=${{ matrix.jdkversion }}
        echo jdk major version $jdkversion
        jdkpostfix=${{ matrix.jdkpostfix }}
        echo jdk postfix $jdkpostfix
        sdk list java
        matchstatement="match(\$0, /($jdkversion\.[0-9]+.[0-9]+.[^ ]+).*$jdkpostfix/, a) {print a[1]}"
        echo matching $matchstatement 
        echo take one
        sdk list java | gawk "match(\$0, /($jdkversion\.[0-9]+.[0-9]+.[^ ]+).*$jdkpostfix/, a) {print a[1]}"
        jsdk=sdk list java | gawk "match(\$0, /($jdkversion\.[0-9]+.[0-9]+.[^ ]+).*$jdkpostfix/, a) {print a[1]}"
        echo downloading jdk $jsdk
        sdk install java $jsdk
        unset JAVA_HOME
        java -Xmx32m -version
        javac -J-Xmx32m -version
