name: SDKman! runner

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdkversion: [8, 11, 12]
        jdkpostfix: [j9-adpt, hs-adpt]
    
    steps:
    - name: Download SDKMAN!
      run: |
        curl -sL https://get.sdkman.io | bash
        echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        jdkversion=${{ matrix.jdkversion }}
        echo jdk major version $jdkversion
        jdkpostfix=${{ matrix.jdkpostfix }}
        echo jdk postfix $jdkpostfix
        JSDK=sdk list java | perl -n -e'/(${{ matrix.jdkversion }}\.\d+\.\d+.\w+).*${{ matrix.jdkpostfix }}/gm && print $1'
        echo found $JSDK
        sdk install java $JSDK
        unset JAVA_HOME
        java -Xmx32m -version
        javac -J-Xmx32m -version
