name: SDKman! runner

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdkversion: [8, 11, 12]
        jdkpostfix: [j9-adpt, hs-adpt]
    
    steps:
    - name: Download SDKMAN!
      run: |
        curl -sL https://get.sdkman.io | bash
        echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        jdkversion=${{ matrix.jdkversion }}
        jdkpostfix=${{ matrix.jdkpostfix }}
        sdk list java
        jsdk=$(sdk list java | gawk "match(\$0, /($jdkversion\.[0-9]+.[0-9]+.$jdkpostfix)/, a) {print a[1]}")
        sdk install java $jsdk
        unset JAVA_HOME
        java -Xmx32m -version
        javac -J-Xmx32m -version
